package example

import (
	"testing"

	"github.com/alexshd/lawtest"
)

// This file was auto-generated by lawtest-gen
// Review and complete the TODO items before running tests

// TODO: Create wrapper function for method Merge
// func WrapMerge(a, b State) State {
//     return a.Merge(b)
// }

func TestMergeImmutability(t *testing.T) {
	// TODO: Create a generator for State
	gen := func() State {
		// TODO: Return a valid instance of State
		panic("implement generator")
	}

	lawtest.ImmutableOp(t, WrapMerge, gen)
}

func TestMergeAssociativity(t *testing.T) {
	// TODO: Verify that Merge SHOULD be associative
	// Question: Does (a op b) op c = a op (b op c) for your operation?
	// If NO, remove this test - not all operations are associative

	gen := func() State {
		// TODO: Return a valid instance of State
		panic("implement generator")
	}

	lawtest.Associative(t, WrapMerge, gen)
}

